image: ubuntu:latest

stages:
  - deploy-client    

deploy production client:
  stage: deploy-client
  image: ruby:latest
  tags:
    - dalfcs_docker_kvm  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$APP_NAME_BACKEND --api-key=$HEROKU_API_KEY --cleanup
  only:
    - main